authentication/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'authentication'

urlpatterns = [
    path('regist', views.register, name='register'),
    path('login', views.inF, name='login'),
    path('logout', views.outF, name='logout'),
]

info/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'info'

urlpatterns = [
   path('DataCovid', views.datalist, name= 'DataCovid'),
   path('getData', views.search),
]
 

story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('feedback.urls')),
    path('',include('produk.urls')),
    path('', include('pesan.urls')),
    path('', include('artikel.urls')),
    path('', include('authentication.urls')),
    path('', include('info.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models

# Create your models here.

authentication/views.py

from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required



# Create your views here.

def register(request):
    if request.method == "POST":
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect('/')
    else:
        form = UserCreationForm()
    return render (request,'regist.html', {'form': form})

def inF(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('/')
    else:
        form = AuthenticationForm()
    return render(request, "login.html", {'form': form})

def outF(request):
    logout(request)
    return redirect('/')

authentication/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
html {
    overflow-x: hidden;
}

.header {
    color: #37676E;
    }

.header h1 {
    font-weight: bolder;
    padding-top: 50px;
    font-size: 90px;
    }

.header span {
    color: #B91A00
}

.header h6 {
    font-size: 22px;
}

.btn-default{
    background-color: #37676E;
    color:#FFF;
}

.btn-default:hover, .btn-default:focus, .btn-default:active, .btn-default.active, .open .dropdown-toggle.btn-default {   
    background-color: #BF3939;
    color:#FFF;
}

.login-section{
    width: 450px;
    padding: 3% 0 0;
    margin: auto;
}

.login-form input{
    font-family: Arial; 
    outline: none;
    width: 100%;
    border: none;
    font-size: 14px;
    background:#f2f2f2;
    padding: 8px;
    margin: 12px;
}

.messages{
    font-size: 10px;
    text-align: center;
    color: #37676E;
}

</style>

  {% if user.is_authenticated %}
    <section id="login" class="text-center section">
      <h3>Halo, kamu sudah sign in :)))</h3>
      <a href="{% url 'authentication:logout' %}">
          <button class="btn btn-primary active" id="logout">Logout</button>
      </a>
    </section>
  
  {% else %}
    <div class="col-12 header text-center">
        <h1>LOG<span>IN</span></h1>
        <h6>Login ke website AADCor untuk mengakses fitur yang terkunci!</h6>
    </div>

    <div class="login-section">
        <div class="login-form">
            <form method="POST" action="{% url 'authentication:login' %}">
            {% csrf_token %}
            {{form.as_table}}
            <div class="col text-center">
                <button type="submit" name ="create" class="btn btn-default text-center">Login</button>
            </div> 
            </form>
            <br>
            <p style = text-align:center>Belum punya akun? Sign Up <a href="{% url 'authentication:register' %}">Disini</a></p>
        </div>
    </div>

    {% endif %}
{% endblock content %}

authentication/templates/regist.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    html {
        overflow-x: hidden;
    }
    
    .header {
    color: #37676E;
    }

    .header h1 {
        font-weight: bolder;
        padding-top: 50px;
        font-size: 90px;
        }

    .header span {
        color: #B91A00
    }

    .header h6 {
        font-size: 22px;
    }

    .btn-default{
        background-color: #37676E;
        color:#FFF;
    }

    .btn-default:hover, .btn-default:focus, .btn-default:active, .btn-default.active, .open .dropdown-toggle.btn-default {   
        background-color: #BF3939;
        color:#FFF;
    }

    .login-section{
        width: 450px;
        padding: 3% 0 0;
        margin: auto;
    }
    
    .login-form input{
        font-family: Arial; 
        outline: none;
        width: 100%;
        border: none;
        font-size: 14px;
        background:#f2f2f2;
        padding: 8px;
        margin: 12px;
    }

    .messages{
        font-size: 10px;
        text-align: center;
        color: #37676E;
    }



</style>

    {% if user.is_authenticated %}
        <section id="login" class="text-center section">
            <h3>Halo kamu sudah sign in :)))</h3>
            <p>Mau sign out?</p>
            <a href="{% url 'authentication:logout' %}">
                <button class="btn btn-primary active" id="logout">Logout</button>
            </a>
        </section>

    {% else %}
        <div class="col-12 header text-center">
            <h1>SIGN<span> IN</span></h1>
            <h6>Daftarkan akun baru ke website AADCor untuk mengakses fitur yang terkunci!</h6>
        </div>

<<<<<<< HEAD
        <section style = "height: 100vh;"> 
            <div class="login-section">
                <div class="login-form">
                    <form method="POST" action="">
                    {% csrf_token %} 
                    {{form.as_table}}  
                    <input type="submit" name = "create" value = "login">
                    </form>
                    <p style = text-align:center> Login <a href="{% url 'authentication:register' %}">Here</a> </p>
=======
        <div class="login-section">
            <div class="login-form">
                <form method="POST" action="">
                {% csrf_token %}
                {{form.as_table}}  
                <div class="col text-center">
                    <br>
                    <button type="submit" name ="create" class="btn btn-default text-center">Daftar</button>
>>>>>>> a56eaaa7a2edbc4605582c878259ceeebb9ecf63
                </div>
                </form>
                <br>
                <p style = text-align:center>Sudah punya akun? Login <a href="{% url 'authentication:login' %}">Disini</a> </p>
            </div>
        </div>

    {% endif %}
{% endblock %}