feedback/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'feedback'

urlpatterns = [
    path('feedback/', views.home, name='home'),
    path('pengalaman/', views.experience, name='pengalaman'),
    path('masalah/', views.prob, name='masalah'),
    path('save/', views.thanks, name='save'),
]

homepage/urls.py
from django.urls import path
from homepage import views

app_name = 'homepage'
urlpatterns = [
    path('', views.home, name='home'),
    # dilanjutkan ...
]

info/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'info'

urlpatterns = [
   path('DataCovid', views.datalist, name= 'DataCovid'),
   path('getData', views.search),
]
 

story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('feedback.urls')),
    path('',include('produk.urls')),
    path('', include('pesan.urls')),
    path('', include('artikel.urls')),
    path('', include('authentication.urls')),
    path('', include('info.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback/models.py
from django.db import models

# Create your models here.
from django.forms import ModelForm, Textarea

# Create your models here.

class exp(models.Model):
    nama = models.CharField('nama', max_length=120, null=True)
    pesan = models.TextField('pesan', max_length=250, null=True)
    
    class Meta:
        db_table = 'exp'

class problem(models.Model):
    nama = models.CharField('nama', max_length=120, null=True)
    masalah = models.TextField('masalah', max_length=250, null=True)
    
    class Meta:
        db_table = 'problem'



feedback/forms.py
from django.core import validators
from django import  forms 
from django.forms import Textarea
from .models import exp, problem

class feedbackform(forms.ModelForm):
    required_css_class = "required"
    class Meta:
        model = exp
        fields = ['nama','pesan']
        widgets ={
                'nama' : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Tuliskan namamu disini...'}),
                'pesan' : forms.Textarea(attrs={'class': 'form-control','rows':10, 'cols':10, 'placeholder': 'Tuliskan pengalaman kamu disini'}),
        }
        labels = {
           'nama' : '',
           'pesan' : '',
        }

class problemform(forms.ModelForm):
    required_css_class = "required"
    class Meta:
        model = problem
        fields = ['nama','masalah']
        widgets ={
                'nama' : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Tuliskan namamu disini...'}),
                'masalah' : forms.Textarea(attrs={'class': 'form-control','rows':10, 'cols':10, 'placeholder': 'Tuliskan pengalaman kamu disini'}),
        }
        labels = {
           'nama' : '',
           'masalah' : '',
        }


feedback/views.py
from django.shortcuts import render, redirect
from .forms import feedbackform, problemform
from .models import exp, problem

from django.http import HttpResponseRedirect
# Create your views here.
def home(request):
    return render(request, 'feedback0.html')
    
def experience(request):
    form = feedbackform(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/save')
    else:
        stud = exp.objects.all()
    return render(request, 'feedback1.html', {'form': form})

def prob(request):
    form = problemform(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/save')
    else:
        stud = problem.objects.all()
    return render(request, 'feedback2.html', {'form': form})

def thanks(request):
    return render(request,'thankyou.html')

feedback/templates/feedback0.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
.form-rounded {
    border-radius: 20px;
}
.btn{
    border-radius: 20px;
}

h3{
    font-size: 60px;
    font-family: Arial;
    font-weight: bold;
    color: #37676E;
    text-align: center;
    margin-top: 150px;
}

.bttn{
    border: none;
    background: none; 
    outline: none; 
    text-decoration: none; 
    align-items: center;
}

@media (max-width: 1400px){
    h3{
        font-size: 40px;
    }
}
</style>

{% if user.is_authenticated %}
    <div class="container h-100" style="height: 100px;">
        <div class="row h-100 justify-content-center align-items-center">
            <h3>Bagaimana</br>pengalamanmu </br> dengan website </br> kami, {{ user|title }}?</h3>
        </div>
            <p>&nbsp;</p>
            <a href="{% url 'feedback:pengalaman' %}" class="bttn" role="button" aria-pressed="true" style="margin-left: 340px; margin-top: 50px;"><img src="{% static 'images/good.svg' %}" width="200" height="200"></a> 
            <a href="{% url 'feedback:masalah' %}" class="bttn" role="button" aria-pressed="true" style="margin-left: 40px; margin-top: 50px;"> <img src="{% static 'images/bad.svg' %}" width="200" height="200"></a> 
            <p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>
    </div>
{% else %}
    <div class="container h-100" style="height: 100px;">
        <div class="row h-100 justify-content-center align-items-center">
            <h3>Bagaimana</br> pengalamanmu </br> dengan website </br> kami ?</h3>
        </div>
            <p>&nbsp;</p>
            <a href="{% url 'feedback:pengalaman' %}" class="bttn" role="button" aria-pressed="true" style="margin-left: 340px; margin-top: 50px;"><img src="{% static 'images/good.svg' %}" width="200" height="200"></a> 
            <a href="{% url 'feedback:masalah' %}" class="bttn" role="button" aria-pressed="true" style="margin-left: 40px; margin-top: 50px;"> <img src="{% static 'images/bad.svg' %}" width="200" height="200"></a> 
            <p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>
    </div>
{% endif %}
{% endblock %} 

feedback/templates/feedback1.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
.form-rounded {
    border-radius: 20px;
}
.btn{
    border-radius: 20px;
}

h3{
    font-size: 60px;
    font-family: Arial;
    font-weight: bold;
    color: #37676E;
}
</style>
<div class="container h-100" style="height: 250px;">
    <div class="row h-100 justify-content-center align-items-center">
    <form class="col-12" method="POST" style="margin-top: 150px;">
        <h3>Boleh ceritakan </br> pengalamanmu ?</h3> </br>
        {% csrf_token %}
        {{form.as_p}}
        <a href="{% url 'feedback:save' %}" >
        <input type="submit" value="Submit" class="btn btn-lg" style='color: white; background-color: #37676E;'></input>
        </a>
        <!--  
        <div class="container">
          <input type="text" class="form-control form-rounded" name = 'nama' placeholder="Nama......."></input>
          <br/>
          <textarea class="form-control form-rounded" name= 'pesan' rows="8"></textarea>
          <br/>     
          <button type="button" class="btn btn-danger btn-sm">Submit</button>
        ---->
    </form>   
    </div>
</div>

{% endblock %} 

feedback/templates/feedback2.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
.form-rounded {
    border-radius: 20px;
}
.btn{
    border-radius: 20px;
}

h3{
    font-size: 60px;
    font-family: Arial;
    font-weight: bold;
    color: #37676E;
}
</style>

<div class="container h-100" style="height: 250px">
    <div class="row h-100 justify-content-center align-items-center">
    <form class="col-12" method="POST" style="margin-top: 150px;">
        <h3>Boleh ceritakan </br> apa masalahmu ?</h3> </br>
        {% csrf_token %}
        {{form.as_p}}
        <a href="{% url 'feedback:save' %}" >
        <input type="submit" value="Submit" class="btn btn-lg" style='color: white; background-color: #37676E;'></input>
        </a>
        <!--  
        <div class="container">
          <input type="text" class="form-control form-rounded" name = 'nama' placeholder="Nama......."></input>
          <br/>
          <textarea class="form-control form-rounded" name= 'pesan' rows="8"></textarea>
          <br/>     
          <button type="button" class="btn btn-danger btn-sm">Submit</button>
        ---->
    </form>   
    </div>
</div>

{% endblock %} 

feedback/templates/navhome.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Bootstrap CSS -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <title>Ada Apa Dengan Corona</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"/>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark" style= "background-color: #37676E;">
    <a class="navbar-brand" href="{% url 'homepage:home' %}"><img src="{% static 'images/kecil.svg' %}" alt="Logo" style="width:100px"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href= "{% url 'homepage:home' %}" style="color: white; ">HOME</a>
      </li>
    </ul>
    </div>
  </nav>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% block content %}
{% endblock %}
</body>
</html>

feedback/templates/thankyou.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    
    .btn{
    border-radius: 20px;
    background-color:#37676E;
    font-size: 17px;
    font-family: 'Varela Round', sans-serif; 
    font-weight: 600;
    border-color: #37676E;
    color: white;
}
</style>

{% if user.is_authenticated %}
    <section style="height: 700px;">
    <div class="container h-100" style="height: 100px;">
        <div class="row h-100 justify-content-center align-items-center">
            <h1>Terima kasih cerita {{ user }} sudah kami terima. Semoga {{user }} sehat selalu.</h1>
            <button class="btn active" type="button" id="GetFile">Get File!</button>
        </div>
    </div>
    </section>

{% else %}
    <section style="height: 700px;">
    <div class="container h-100" style="height: 100px;">
        <div class="row h-100 justify-content-center align-items-center">
            <h1>Terima kasih cerita Anda sudah kami terima</h1>
            <button class="btn active" type="button" id="GetFile">Get File!</button>

        </div>
    </div>
    </section>


{% endif %}

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript"src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript">

$('#GetFile').on('click', function () {
    $.ajax({
        url: 'https://www.cdc.gov/coronavirus/2019-ncov/prevent-getting-sick/prevention-H.pdf',
        method: 'GET',
        xhrFields: {
            responseType: 'blob'
        },
        success: function (data) {
            var a = document.createElement('a');
            var url = window.URL.createObjectURL(data);
            a.href = url;
            a.download = 'PreventCorona101.pdf';
            document.body.append(a);
            a.click();
            a.remove();
            window.URL.revokeObjectURL(url);
        }
    });
    });
</script>
{% endblock %} 