info/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'info'

urlpatterns = [
   path('DataCovid', views.datalist, name= 'DataCovid'),
   path('getData', views.search),
]
 

produk/urls.py
from django.urls import path
from . import views

app_name = "produk"

urlpatterns = [
    path('produk/', views.produk, name='produk'),
    path('cart/', views.cart, name='cart'),
    path('createadmin/', views.createadmin, name='createadmin'),
    path('updateitem/', views.updateitem, name='updateitem'),
    path('checkout/', views.checkout, name='checkout'),
    path('cari-produk/', views.find_produk),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('feedback.urls')),
    path('',include('produk.urls')),
    path('', include('pesan.urls')),
    path('', include('artikel.urls')),
    path('', include('authentication.urls')),
    path('', include('info.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produk/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name = 'customer', null=True, blank=True)
    name = models.CharField(max_length=150, null=True)
    name = models.CharField(max_length=150, null=True)

    def __str__(self):
        return self.name

class Produk(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(null = True, blank=True)
    desc = models.TextField(blank=True)

    def __str__(self):
        return self.name
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except :
            url = ''
        return url

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False,null=True, blank=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)
    
    @property
    def get_cart_total(self):
        orderitems = self.cart_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.cart_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

class Cart(models.Model):
    product = models.ForeignKey(Produk, on_delete=models.SET_NULL, blank=True,null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total
    
    

produk/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .models import Customer, Produk, Order, Cart
from django.contrib.auth.models import User
import json
from django.core import serializers

# Create your views here.
def produk(request):
    if request.user.is_authenticated:
        customer, created = Customer.objects.get_or_create(user=request.user)
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.cart_set.all()
        cartitems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0}
        cartitems = order['get_cart_items']
    produk = Produk.objects.all()
    return render(request, 'produk.html', {'produk':produk, 'cartitems':cartitems})

def cart(request):
    if request.user.is_authenticated:
        customer, created = Customer.objects.get_or_create(user=request.user)
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.cart_set.all()
    else:
        items = []
        order = {'get_cart_total':0}
    return render(request, 'cart.html', {'items':items, 'order':order})

def createadmin(request):
    if not User.objects.filter(username="admin").exists():
        user = User.objects.create_user(username="admin", password="aadc", first_name="ada apa", last_name="dengan corona")
        user.is_superuser = True
        user.is_staff = True
        user.save()
        return redirect("../")
    else:
        return redirect("../")

def updateitem(request):
    data = json.loads(request.body)
    prodId = data['prodId']
    action = data['action']

    print("Action: ", action)
    print("Product ID: ", prodId )

    customer = request.user.customer
    product = Produk.objects.get(id=prodId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    cart, created = Cart.objects.get_or_create(order=order,product=product)

    if action == "add":
        cart.quantity += 1
    elif action == 'remove':
        cart.quantity -= 1

    cart.save()

    if action == 'delete' or cart.quantity <= 0:
        cart.delete()

    print(cart.quantity)
    return JsonResponse('Item was added', safe=False)

def checkout(request):
    Cart.objects.all().delete()
    return render(request, "checkout.html")

def find_produk(request):
    produk = Produk.objects.all()
    json_data_produk = serializers.serialize("json", produk)
    return HttpResponse(json_data_produk, content_type="application/json")

produk/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    .header h1{
        color: #37676E;
        font-weight: bolder;
        font-size: 70px;
        padding-top: 90px;
    }
    .d-flex img{
        width: 130px;
    }
    .d-flex .flex-column {
        padding-right: -40px;
    }
    p span {
        margin-right: auto;
    }
    .checkout {
        background-color: #37676E;
        color: white;
    }
    .checkout:hover {
        background-color: white;
        border-color: #37676E;
        color: #37676E;
    }
    .lanjut {
        border-color: #37676E;
        color: #37676E;
    }
    .lanjut:hover {
        background-color: #37676E;
        color: white;
    }
    a.update-cart {
        height: 15px;
    }
    
</style>

<div class="container">
    <div class="row">
        <div class="col-12 header">
            <h1>KERANJANG</h1>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-lg-7 col-md-12 col-sm-12">
            {% for item in items %}
            <div class="d-flex">
                <div class="d-flex flex-column mr-5"><img src="{{ item.product.imageURL }}" alt="{{ item.product.name }}"></div>
                <div class="d-flex flex-column ml-3">
                    <p><strong>Items:</strong> {{ item.product.name}}</p>
                    <p><strong>Harga:</strong> Rp{{ item.product.price|floatformat:3 }}</p>
                    <div class="d-flex flex-row pb-1">
                        <p class="my-auto"><strong>Qty:</strong> {{ item.quantity }}</p>
                        <div class="d-flex flex-column pl-2 pb-3">
                            <a data-product={{item.product.id}} data-action="add" class="update-cart"><i class="fas fas fa-caret-up"></i></a>
                            <a data-product={{item.product.id}} data-action="remove" class="update-cart"><i class="fas fa-caret-down"></i></a>
                        </div>
                    </div>
                    <p><strong>Total:</strong> Rp{{ item.get_total|floatformat:3 }}</p>
                </div>
                <div class="d-flex flex-column ml-auto my-auto mr-3">
                    <a data-product={{item.product.id}} data-action="delete" class="update-cart"><i style="color:#B91A00 ;" class="fas fa-times	"></i></a>
                </div>
            </div>
            <hr>
            {% endfor %}
        </div>
        <div class="col-lg-4 col-md-12 col-sm-12 ml-5">
            <p>Subtotal <span class="float-right">Rp{{order.get_cart_total|floatformat:3}}</span></p>
            <hr>
            <p>Ongkos Kirim <span class="float-right">Gratis</span></p>
            <hr>
            <p><strong>Total <span class="float-right">Rp{{order.get_cart_total|floatformat:3}}</span></strong></p>
            <br><br><br><br>
            <a href="{% url 'produk:produk' %}" class="btn lanjut">Lanjut Belanja</a>
            <a href="{% url 'produk:checkout' %}" class="btn float-right checkout">Checkout</a>
        </div>
    </div>
    
</div>

{% endblock content %}

produk/templates/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    .col-12 {
        padding-top: 200px;
        color: white;
    }
    h1 {
        font-weight: bolder;
        font-size: 90px;   
    }
    .card {
        background-color: #37676eb8;
        border-radius: 20px;
        border: none;
        width: 55%;
    }
</style>
<div class="col-12">
    <div class="card p-5 mx-auto">
        <img src="{% static 'images/kecil.svg' %}" alt="logo">
        <h1 class="mx-auto">Terima <span style="color: #B91A00;">Kasih!</span></h1>
        <h4 class="mr-auto ml-auto">Pesanan Anda sedang kami proses. #StaySafe!</h4>
    </div>
</div>
{% endblock content %}

produk/templates/produk.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    .header {
        color: #37676E;
        padding-top: 90px;
    }
    .header h1 {
        font-weight: bolder;
        font-size: 90px;}
    .header span {
        color: #B91A00
    }
    .header h6 {
        font-size: 22px;
    }
    .harga {
        font-size: 17px;
        padding-top: 5px;
    }
    .btn {
        background-color: #37676E;
        color: white;
    }
    .btn:hover {
        background-color: white;
        color: #37676E;
        border-color: #37676E;
    }
    .cart img {
        margin-top: 123px;
        margin-right: 30px;
        width: 6%;
        float: right; 
    }
    .card {
        border-color: #37676E;
        border-width: 2px;
        border-radius: 10px;
    }
    .header p {
        margin-bottom: -0.5rem;
        color: #B91A00;
    }
    .cart {
        padding-right: 27px;
    }
    #search {
    width: 45px;
    background-color:#37676E;
    border-color: #37676E;
    text-align: center;
    border: none;
    color: white;
    }
    #search:hover {
        color:#37676E;
        background-color: transparent;
    }

</style>

<div class="container">
    <div class="row header">
        <div class="col-6">
            <h1>PRO<span>DUK</span></h1>
            <h6>yang kamu butuhkan untuk menjalani #NewNormal</h6>
        </div>
        <div class="col-6 text-right justify-content-right pt-5">
            <p><strong class="p-1" style="background-color: #B91A00; color: white; border-radius: 50%;">{{cartitems}}</strong></p>
            <a class="cart" href="{% url 'produk:cart' %}"><i class="fas fa-shopping-cart fa-2x" style="color: #37676E;"></i></a>
            <div class="d-flex justify-content-center mt-3">
                <input class= "form-control" id="keyword" placeholder="Produk yang kamu cari...">
                <button type="button" id="search" class="form-control ml-3"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </div>
    <div class="row align-item-center mb-5">
        {% for product in produk %}
        <div class="col-lg-4 col-md-12 col-sm-12 mt-5">
            <div class="card p-2" style="width: 21rem; height: max-content;">
                <img src="{{ product.imageURL }}" class="card-img-top p-4" alt="{{product.name}}">
                <div class="card-body">
                  <h5 class="card-title">{{ product.name }}</h5>
                  <p class="card-text">{{ product.desc }}</p>
                  <button data-product={{product.id}} data-action="add" class="btn add-btn update-cart">Masukkan Keranjang</button>
                  <h5 class="pt-2 float-right harga">Rp{{ product.price|floatformat:3 }}</h5>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

produk/templates/produk_search.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    .header {
        color: #37676E;
        padding-top: 90px;
    }
    .header h1 {
        font-weight: bolder;
        font-size: 90px;}
    .header span {
        color: #B91A00
    }
    .header h6 {
        font-size: 22px;
    }
    .harga {
        font-size: 17px;
        padding-top: 5px;
    }
    .btn {
        background-color: #37676E;
        color: white;
    }
    .btn:hover {
        background-color: white;
        color: #37676E;
        border-color: #37676E;
    }
    .cart img {
        margin-top: 123px;
        margin-right: 30px;
        width: 6%;
        float: right; 
    }
    .card {
        border-color: #37676E;
        border-width: 2px;
        border-radius: 10px;
    }
    .header p {
        margin-bottom: -0.5rem;
        color: #B91A00;
    }
    .cart {
        padding-right: 27px;
    }
    #search {
    width: 45px;
    background-color:#37676E;
    border-color: #37676E;
    text-align: center;
    border: none;
    color: white;
    }
    #search:hover {
        color:#37676E;
        background-color: transparent;
    }

</style>

<div class="container">
    <div class="row header">
        <div class="col-6">
            <h1>PRO<span>DUK</span></h1>
            <h6>yang kamu butuhkan untuk menjalani #NewNormal</h6>
        </div>
        <div class="col-6 text-right justify-content-right pt-5">
            <p><strong class="p-1" style="background-color: #B91A00; color: white; border-radius: 50%;">{{cartitems}}</strong></p>
            <a class="cart" href="{% url 'produk:cart' %}"><i class="fas fa-shopping-cart fa-2x" style="color: #37676E;"></i></a>
            <div class="d-flex justify-content-center mt-3">
                <input class= "form-control" id="keyword" placeholder="Produk yang kamu cari...">
                <button type="button" id="search" class="form-control ml-3"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </div>




{% endblock content %}