artikel/urls.py
from . import views
from django.urls import path

app_name = "artikel"

urlpatterns = [
    path('artikel/', views.artikelPage, name='home'),
    path('artikel/<slug:slug>/', views.formCom, name='post_detail'),
]

feedback/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'feedback'

urlpatterns = [
    path('feedback/', views.home, name='home'),
    path('pengalaman/', views.experience, name='pengalaman'),
    path('masalah/', views.prob, name='masalah'),
    path('save/', views.thanks, name='save'),
]

info/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'info'

urlpatterns = [
   path('DataCovid', views.datalist, name= 'DataCovid'),
   path('getData', views.search),
]
 

pesan/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'pesan'

urlpatterns = [
    path('pesan/', views.home, name='home'),
    path('datas/', views.experience, name='isi'),
    path('res/', views.hasil, name='res'),
    path('res2/', views.hasil2, name='res2'),
    path('search/', views.search, name='search'),
]

produk/urls.py
from django.urls import path
from . import views

app_name = "produk"

urlpatterns = [
    path('produk/', views.produk, name='produk'),
    path('cart/', views.cart, name='cart'),
    path('createadmin/', views.createadmin, name='createadmin'),
    path('updateitem/', views.updateitem, name='updateitem'),
    path('checkout/', views.checkout, name='checkout'),
    path('cari-produk/', views.find_produk),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('feedback.urls')),
    path('',include('produk.urls')),
    path('', include('pesan.urls')),
    path('', include('artikel.urls')),
    path('', include('authentication.urls')),
    path('', include('info.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Bootstrap CSS -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <link rel="icon" href="{% static 'images/kecil.svg' %}"/>
    <title>Ada Apa Dengan Corona</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"/>
    <script src="https://kit.fontawesome.com/4ee029818e.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
      var user = '{{request.user}}'

      function getToken(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getToken('csrftoken');
    </script>

  <style>
  #content {
    padding-top: 50px;
    padding-left: 100px;
    padding-right: 100px;
    padding-bottom: 50px;
    overflow: hidden;
  }

  #content img {
    width: 350px;
    margin-right: 100px;
    float: left;
  }

  #content h6{
    margin-left: 15px;
    display: block;
    color:white;
  }
  </style>
</head>
<body>
  {% if user.is_authenticated %}
  <nav class="navbar navbar-expand-lg navbar-dark" style= "background-color: #37676E;">
    <a class="navbar-brand" href="{% url 'homepage:home' %}"><img src="{% static 'images/kecil.svg' %}" alt="Logo" style="width:100px"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" style="color: white; "> {{ user|upper }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'produk:produk' %}"style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; color: white;">PRODUK</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'info:DataCovid' %}"style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; color: white;">STATISTIK</a>
      </li>
      <li class="nav-item">
        <li class="dropdown">
          <a class="dropdown-toggle nav-link" data-toggle="dropdown" href="{% url 'pesan:isi' %}" style="color: white; font-size: 18px;">PESAN
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'pesan:isi' %}" class="nav-link" style="color:black; ">Isi Pesan</a></li>
            <li><a href="{% url 'pesan:res' %}" class="nav-link" style="color:black; ">Cari Pesan</a></li>
            <li><a href="{% url 'pesan:res2' %}" class="nav-link" style="color:black; ">Data Pesan</a></li>
          </ul>
        </li>
      </li>
      <li class="nav-item">
        <a class="nav-link" href= "{% url 'artikel:home' %}" style="color: white; ">ARTIKEL</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href= "{% url 'feedback:home' %}" style="color: white; ">FEEDBACK</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'authentication:logout' %}"style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; color: white;">SIGN OUT</a>
      </li>
    </ul>
    </div>
  </nav>
  {% else %}
  <nav class="navbar navbar-expand-lg navbar-dark" style= "background-color: #37676E;">
    <a class="navbar-brand" href="{% url 'homepage:home' %}"><img src="{% static 'images/kecil.svg' %}" alt="Logo" style="width:100px"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'produk:produk' %}"style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; color: white;">PRODUK</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'info:DataCovid' %}"style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; color: white;">STATISTIK</a>
      </li>
      <li class="nav-item">
        <li class="dropdown">
          <a class="dropdown-toggle nav-link" data-toggle="dropdown" href="{% url 'pesan:isi' %}" style="color: white; font-size: 18px;">PESAN
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'pesan:isi' %}" class="nav-link" style="color:black; ">Isi Pesan</a></li>
            <li><a href="{% url 'pesan:res' %}" class="nav-link" style="color:black; ">Cari Pesan</a></li>
            <li><a href="{% url 'pesan:res2' %}" class="nav-link" style="color:black; ">Data Pesan</a></li>
          </ul>
        </li>
      </li>
      <li class="nav-item">
        <a class="nav-link" href= "{% url 'artikel:home' %}" style="color: white; ">ARTIKEL</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href= "{% url 'feedback:home' %}" style="color: white; ">FEEDBACK</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'authentication:login' %}"style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; color: white;">SIGN IN</a>
      </li>
    </ul>
    </div>
  </nav>
{% endif %}
{% block content %}
{% endblock content %}

<p>&nbsp;</p>
<footer style="background-color: #37676E;">
  <div id="content">
    <img src="{% static 'images/logo2.svg' %}" alt="Logo" style="width:300px">
    <p style="line-height: 1.7rem; font-style: italic; color:white; padding-top: 70px">“Web ini bertujuan untuk memberikan wawasan kepada masyarakat tentang Covid-19 yang berada di Indonesia 
      yang berisi berita dan data. Manfaat dari website ini adalah orang yang mengunjungi website ini akan menerima informasi tentang Covid-19 
      dan bisa membeli produk yang dibutuhkan untuk menghadapi virus Covid-19.”
    </p>
    <h6 style="line-height: 1.7rem; color:white;">- Tim AADCor (AdaApaDenganCorona)</h6>
    <p>&nbsp;</p>
  </div>
</footer>

<script src= https://code.jquery.com/jquery-3.1.1.min.js></script> 
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</body>
</html>